wineot_search_homepage:
    path:     /
    defaults: { _controller: WineotFrontEndSearchBundle:Search:search }
wineot_search_result:
    path:     /search
    defaults: { _controller: WineotFrontEndSearchBundle:Search:searchResult }

