wineot_front_end_winery_show:
    path:     /{wineryName}_{wineryId}
    defaults: { _controller: WineotFrontEndWineryBundle:Winery:show }
wineot_front_end_winery_winelist:
    path:     /{wineryName}_{wineryId}/list
    defaults: { _controller: WineotFrontEndWineryBundle:Winery:listWine }
wineot_front_end_winery_own:
    path:     /{wineryId}/own
    defaults: { _controller: WineotFrontEndWineryBundle:Winery:own }
wineot_front_end_winery_best_rated:
    path:     /{wineryName}_{wineryId}/bestrated
    defaults: { _controller: WineotFrontEndWineryBundle:Winery:bestRated }
