wineot_front_end_winery_show:
    path:     /{wineryName}_{wineryId}
    defaults: { _controller: WineotFrontEndWineryBundle:Winery:show }
wineot_front_end_winery_edit:
    path:     /{wineryName}_{wineryId}/edit
    defaults: { _controller: WineotFrontEndWineryBundle:Winery:edit }
wineot_front_end_winery_winelist:
    path:     /{wineryName}_{wineryId}/wines
    defaults: { _controller: WineotFrontEndWineryBundle:Winery:listWines }
wineot_front_end_winery_own:
    path:     /{wineryId}/own
    defaults: { _controller: WineotFrontEndWineryBundle:Winery:own }
wineot_front_end_winery_best_rated:
    path:     /{wineryName}_{wineryId}/bestrated
    defaults: { _controller: WineotFrontEndWineryBundle:Winery:bestRated }
wineot_front_end_winery_owning_show:
    path:     /{wineryName}_{wineryId}/dashboard
    defaults: { _controller: WineotFrontEndWineryBundle:WineryOwner:show }
wineot_front_end_winery_owning_list:
    path:     /ownings
    defaults: { _controller: WineotFrontEndWineryBundle:WineryOwner:list }
