NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
wineot_rest:
    type : rest
    resource: "@WineotRestBundle/Resources/config/routing.yml"
    prefix : /api
wineot_front_end_landing:
    resource: "@WineotFrontEndLandingBundle/Resources/config/routing.yml"
    prefix:   /
wineot_front_end_winery:
    resource: "@WineotFrontEndWineryBundle/Resources/config/routing.yml"
    prefix:   /winery
wineot_front_end_wine:
    resource: "@WineotFrontEndWineBundle/Resources/config/routing.yml"
    prefix:   /winery/{wineryName}/wine
wineot_front_end_comment:
    resource: "@WineotFrontEndCommentBundle/Resources/config/routing.yml"
    prefix:   /comment
wineot_back_end_crud:
    resource: "@WineotBackEndCRUDBundle/Resources/config/routing.yml"
    prefix:   /admin/crud
wineot_front_end_home:
    resource: "@WineotFrontEndHomeBundle/Resources/config/routing.yml"
    prefix:   /home
wineot_back_end_home:
    resource: "@WineotBackEndBackEndBundle/Resources/config/routing.yml"
    prefix:   /admin
wineot_search:
    resource: "@WineotFrontEndSearchBundle/Resources/config/routing.yml"
    prefix:   /
wineot_user:
    resource: "@WineotUserBundle/Resources/config/routing.yml"
    prefix:   /user
wineot_styleguide:
    resource: "@WineotStyleGuideBundle/Resources/config/routing.yml"
    prefix:   /