wineot_search:
    resource: "@WineotFrontEndSearchBundle/Resources/config/routing.yml"
    prefix:   /

wineot_user:
    resource: "@WineotUserBundle/Resources/config/routing.yml"
    prefix:   /user

wineot_front_end_home:
    resource: "@WineotFrontEndHomeBundle/Resources/config/routing.yml"
    prefix:   /

wineot_styleguide:
    resource: "@WineotStyleGuideBundle/Resources/config/routing.yml"
    prefix:   /

wineot_landing_page_home:
    resource: "@WineotLandingPageHomeBundle/Resources/config/routing.yml"
    prefix:   /