security:
    encoders:
        Wineot\DataBundle\Document\User:
            algorithm:        md5
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        default_provider:
            mongodb: { class: Wineot\DataBundle\Document\User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            provider: default_provider
            anonymous: ~
            form_login:
                login_path:  wineot_user_login
                check_path:  wineot_user_login_check
            logout:
                path:     wineot_user_logout
                target:   wineot_front_end_homepage

    access_control:
        - { path: ^/user/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/favorite, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/unfavorite, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/, roles: ROLE_USER }
        - { path: ^/admin/, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
