wineot_front_end_wine_show:
    path:     /{wineName}_{wineId}_{vintage}
    defaults: { _controller: WineotFrontEndWineBundle:Wine:show, vintage: null }
wineot_front_end_wine_favorite:
    path:     /{wineId}
    defaults: { _controller: WineotFrontEndWineBundle:Wine:favorite }
