wineot_front_end_wine_show:
    path:     /{wineName}/{vintage}/{vintageId}
    defaults: { _controller: WineotFrontEndWineBundle:Wine:show }
wineot_front_end_wine_redirect:
    path:     /{wineName}/{wineId}
    defaults: { _controller: WineotFrontEndWineBundle:Wine:redirectWine }
wineot_front_end_wine_trends:
    path:     /trends
    defaults: { _controller: WineotFrontEndWineBundle:Wine:trends, wineryName: all }
wineot_front_end_wine_best_rated:
    path:     /best-rated
    defaults: { _controller: WineotFrontEndWineBundle:Wine:bestRated, wineryName: all }
