wineot_front_end_wine_show:
    path:     /{wineName}/{wineId}
    defaults: { _controller: WineotFrontEndWineBundle:Wine:show}
wineot_front_end_wine_vintage_show:
    path:     /{wineName}/{vintage}/{vintageId}
    defaults: { _controller: WineotFrontEndWineBundle:Vintage:show}
wineot_front_end_wine_trends:
    path:     /trends
    defaults: { _controller: WineotFrontEndWineBundle:Wine:trends, wineryName: all }
