parameters:
#    wineot_front_end_home.example.class: Wineot\FrontEnd\HomeBundle\Example

services:
#    wineot_front_end_home.example:
#        class: %wineot_front_end_home.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
